version: '3.8'

services:
  db:
    image: postgres:16
    container_name: cnab_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: key142398
      POSTGRES_DB: CNABDataBase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  cnab.webapi:
    image: ${DOCKER_REGISTRY-}cnabwebapi
    build:
      context: .
      dockerfile: src/CNAB.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;User Id=postgres;Password=key142398;Database=CNABDataBase
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db

volumes:
  pgdata: